"""Initial migration

Revision ID: 711c4151400d
Revises: 
Create Date: 2024-08-01 22:46:28.694502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711c4151400d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('argent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('task_ids', sa.JSON(), nullable=False),
    sa.Column('task_orders', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocole',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('principle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_required', sa.Integer(), nullable=True),
    sa.Column('time_unit', sa.String(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('benefits', sa.Integer(), nullable=True),
    sa.Column('selling_time', sa.String(), nullable=True),
    sa.Column('selling_time_unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resource',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('protocole_consumable',
    sa.Column('protocole_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['protocole_id'], ['protocole.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('protocole_id', 'resource_id')
    )
    op.create_table('protocole_material',
    sa.Column('protocole_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['protocole_id'], ['protocole.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('protocole_id', 'resource_id')
    )
    op.create_table('protocole_prerequisite',
    sa.Column('protocole_id', sa.String(), nullable=False),
    sa.Column('prerequisite_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['protocole.id'], ),
    sa.ForeignKeyConstraint(['protocole_id'], ['protocole.id'], ),
    sa.PrimaryKeyConstraint('protocole_id', 'prerequisite_id')
    )
    op.create_table('protocole_protection',
    sa.Column('protocole_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['protocole_id'], ['protocole.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('protocole_id', 'resource_id')
    )
    op.create_table('subprotocole',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('protocole_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['protocole_id'], ['protocole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('principle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_required', sa.Integer(), nullable=True),
    sa.Column('time_unit', sa.String(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('plan_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('benefits', sa.Integer(), nullable=True),
    sa.Column('selling_time', sa.String(), nullable=True),
    sa.Column('selling_time_unit', sa.String(), nullable=True),
    sa.Column('recurrence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.Column('progression', sa.Float(), nullable=True),
    sa.Column('protocole_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('resource_percentage', sa.Float(), nullable=True),
    sa.Column('impact_percentage', sa.Float(), nullable=True),
    sa.Column('complexity_percentage', sa.Float(), nullable=True),
    sa.Column('alignment_percentage', sa.Float(), nullable=True),
    sa.Column('urgency_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['protocole_id'], ['protocole.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sub_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_consumable',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'resource_id')
    )
    op.create_table('task_material',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'resource_id')
    )
    op.create_table('task_prerequisite',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('prerequisite_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'prerequisite_id')
    )
    op.create_table('task_protection',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_protection')
    op.drop_table('task_prerequisite')
    op.drop_table('task_material')
    op.drop_table('task_consumable')
    op.drop_table('sub_task')
    op.drop_table('task')
    op.drop_table('subprotocole')
    op.drop_table('protocole_protection')
    op.drop_table('protocole_prerequisite')
    op.drop_table('protocole_material')
    op.drop_table('protocole_consumable')
    op.drop_table('user')
    op.drop_table('resource')
    op.drop_table('protocole')
    op.drop_table('liste')
    op.drop_table('argent')
    # ### end Alembic commands ###
